[Feature] Header 컴포넌트 구현
gdg-hongik-univ/wow-design-system pull request #167
Opened 2024-09-21 12:24 UTC by ghdtjgus76

## 🎉 변경 사항
Header 컴포넌트 구현했습니다.

## 🚩 관련 이슈
- #164 

### 🙏 여기는 꼭 봐주세요!
지금 피그마에 토큰에 없는 타이포그래피를 사용한 부분이 있어 린님께 요청드려놨습니다!
이 부분 변경해주시면 바로 반영해두겠습니다~

2024-10-02 07:31 UTC, hamo-o requested changes
수고하셨습니다!

2024-10-02 07:31 UTC, hamo-o commented on packages/wow-ui/src/components/Header/Header.stories.ts
> +    },
p4; 아래 경고가 자꾸 떠서 [공식문서](https://storybook.js.org/docs/api/arg-types#controltype) 확인해 봤더니 문서 형식을 조금 바꿔야 할 것 같아요. 저도 다른 컴포넌트에서 수정해야 할 것 같네요 ..

<img width="497" alt="image" src="https://github.com/user-attachments/assets/a4dc7048-9ebb-43ee-9701-ad86865c30cc">

```suggestion
  variant: {
      control: {
        type: "select",
      },
      options: ["username", "login", "none"],
      table: {
        type: { summary: "username | login | none" },
      },
      description:
        '헤더 종류를 나타냅니다. variant가 "username"인 경우 오른쪽에 사용자 이름을, "login"인 경우 로그인 버튼을, "none"인 경우 아무것도 표시하지 않습니다.',
    },
```

2024-10-02 07:31 UTC, hamo-o commented on packages/wow-ui/src/components/Header/index.tsx
> +            </div>
p2;
`role="heading"`과 `aria-level`을 사용하는 것보다는 [시멘틱 태그를 사용하는 것이 더 적합](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/heading_role#best_practices)하다고 합니다.
묶어서 로고 부분 다 `h1`으로 감싸고 본문은 `h2` 이하로 제목을 작성해야 한다고 안내하거나, 아예 요 부분을 일반 태그로 전환하거나 해야 할 것 같아요.

2024-10-10 05:53 UTC, ghdtjgus76 commented on packages/wow-ui/src/components/Header/Header.stories.ts
> +    },
아하 수정해뒀습니다!

2024-10-10 05:56 UTC, ghdtjgus76 commented on packages/wow-ui/src/components/Header/index.tsx
> +            </div>
넵 좋습니다~ 수정해둘게요

2024-10-12 07:57 UTC, SeieunYoo approved these changes
수고하셨습니다~~ 요것도 changeset 만들어주실 수 있을까요? 
지금 나와있는 release PR 이랑 같이 나가도 좋을 거 같아요

2024-10-12 14:56 UTC, hamo-o approved these changes

2024-10-13 07:32 UTC, merged