[Fix] TextField 컴포넌트 error, success 상태 typing 상태와 분리하도록 수정
gdg-hongik-univ/wow-design-system pull request #89
Opened 2024-07-20 04:20 UTC by ghdtjgus76

## 🎉 변경 사항

TextField 컴포넌트에서 기존에는 typing 상태와 error, success 상태를 같이 관리했었는데, 별도로 분리해서 관리하도록 수정했습니다.

## 🚩 관련 이슈
- #87 

### 🙏 여기는 꼭 봐주세요!
현영님이 남겨주신 제어 컴포넌트, 비제어 컴포넌트 관련해서는 어떻게 할지 조금만 생각해보고 다른 PR로 올려볼게요!

2024-07-23 08:00 UTC, SeieunYoo reviewed
수고하셨습니닷~~

2024-07-23 08:00 UTC, SeieunYoo commented on packages/wow-ui/.storybook/main.ts
> -  },
ask;
요 부분은 스토리북 에러 때문에 삭제하신 걸까요?

2024-07-23 08:29 UTC, ghdtjgus76 commented on packages/wow-ui/.storybook/main.ts
> -  },
넵 스토리북 버전 업하면서 설정 파일은 따로 안 건드렸었는데 들어가보니까 에러 발생해서 지웠습니다!

2024-07-25 06:59 UTC, ghdtjgus76 commented
@SeieunYoo 
Checkbox, Switch, MultiGroup 쪽에서 웹접근성 테스트 관련 이슈가 있어서 aria-checked를 checked로 변경했습니다!
그래서 테스트 코드도 이에 맞춰서 조금 수정했는데 확인 부탁드려요!

2024-07-25 08:17 UTC, eugene028 commented
오 드디어 테스트가 통과하는군요오 🥹

2024-07-25 08:21 UTC, SeieunYoo approved these changes
수고 많으셨어요🥹 드디어 모든 액션 통과,,

2024-07-25 08:25 UTC, SeieunYoo requested changes
요거 wow-ui 에 대한 changeset도 작성해주실 수 있을까용 텍스트필드 수정버전도 배포되면 좋을 거 같아서요!

2024-07-25 08:27 UTC, eugene028 approved these changes
수고하셨습니다! TextField도 시간이 된다면 세은님이 작업했던 제어/비제어 컴포넌트 관련 작업해보아도 좋을 것 같아요~

2024-07-25 08:27 UTC, eugene028 commented on packages/wow-ui/src/components/Checkbox/Checkbox.test.tsx
> +    expect(checkbox).not.toBeChecked();
이전에 통과 잘 되었었다가 갑자기 이런걸로 터지는게 뭔가뭔가네요.. 해결 잘 되어서 다행입니닷

2024-07-25 08:28 UTC, eugene028 commented
TextField 관련된 UI 와온에 바로 반영가능하게끔 changeset도 같이 작성해주실 수 있나용?

2024-07-25 08:28 UTC, ghdtjgus76 commented
> 수고하셨습니다! TextField도 시간이 된다면 세은님이 작업했던 제어/비제어 컴포넌트 관련 작업해보아도 좋을 것 같아요~

넵! 그 부분도 곧 반영해두겠습니다~

2024-07-25 08:37 UTC, SeieunYoo approved these changes
머지~~

2024-07-25 08:41 UTC, merged